service: aws-node # NOTE: update this with your service name

frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  region: us-east-1
  stackName: aws-node-lambda
  runtime: nodejs16.x
  versionFunctions: false
  memorySize: 128

functions:
  hello:
    handler: handler.hello
